// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bisljhjbpgeemwtggrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpc2xqaGpicGdlZW13dGdncm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MzMyNTYsImV4cCI6MjA1MDQwOTI1Nn0.DpPuTZ8ye7WCesgrpNO6dxS_JrmtppYgkUaae9r-tFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);